# -*- coding: utf-8 -*-
"""
/***************************************************************************
 leaflet
                                 A QGIS plugin
 Load a webmap directly into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-11
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Tom Chadwin
        email                : tom.chadwin@nnpa.org.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os, random
from datetime import datetime

from PyQt5.QtCore import QDir

from qgis.core import (QgsVectorLayer,
                       QgsPointXY,
                       QgsFeature,
                       QgsGeometry,
                       QgsProject,
                       QgsRectangle,
                       QgsCoordinateReferenceSystem,
                       QgsCoordinateTransform)

def detectLeaflet(mainframe):
    detectResult = mainframe.evaluateJavaScript("L.version")
    if detectResult is None:
        result = False
    else:
        result = True
    return result

def getLeafletMap(mainframe, iface):
    scriptFolder = os.path.join(os.path.dirname(__file__), "js")

    scriptPath = os.path.join(scriptFolder, "getLeafletMap.js")
    with open(scriptPath, 'r') as scriptFile:
        script = scriptFile.read()
    lyrs = None
    lyrs = mainframe.evaluateJavaScript(script)
    while lyrs is None:
        print("Retrieving layers")
    for count, lyr in enumerate(lyrs):
        if lyr[0] == "xyz":
            print("xyz")
            xyzUrl = lyr[1].replace("{s}", random.choice("abc")).replace("{r}",
                                                                         "")
            for opt, val in lyr[2].items():
                # print(opt, val)
                try:
                    xyzUrl = xyzUrl.replace("{" + opt + "}", val)
                except:
                    pass
            iface.addRasterLayer("type=xyz&url=" + xyzUrl, xyzUrl, "wms")
        elif lyr[0] == "vector":
            print("vector")
            tempDir = os.path.join(
                unicode(QDir.tempPath()),
                'web2qgis',
                datetime.now().strftime("%Y_%m_%d-%H_%M_%S_%f"))
            if not QDir(tempDir).exists():
                QDir().mkpath(tempDir)
            vectorPath = os.path.join(tempDir,
                                      "vector" + str(count) + ".geojson")
            with open(vectorPath, 'w') as vectorFile:
                vectorFile.write(lyr[1])
            vectorLayer = QgsVectorLayer(vectorPath,
                                         "vector" + str(count),
                                         "ogr")
             
            # Update extent of the layer
            vectorLayer.updateExtents()
             
            # Add the layer to the Layers panel
            QgsProject.instance().addMapLayers([vectorLayer])
        else:
            print("Unsupported layer type")

    scriptPath = os.path.join(scriptFolder, "getLeafletView.js")
    with open(scriptPath, 'r') as scriptFile:
        script = scriptFile.read()
    extent = None
    extent = mainframe.evaluateJavaScript(script)
    while extent is None:
        print("Retrieving extent")
    xMin, yMin, xMax, yMax = extent.split(",")
    canvas = iface.mapCanvas()
    xform = QgsCoordinateTransform(QgsCoordinateReferenceSystem(4326),
                                   canvas.mapSettings().destinationCrs(),
                                   QgsProject.instance())
    srcExtent = QgsRectangle(float(xMin), float(yMin),
                             float(xMax), float(yMax))
    dstExtent = xform.transformBoundingBox(srcExtent)
    canvas.setExtent(dstExtent)
    canvas.refresh()
