# -*- coding: utf-8 -*-
"""
/***************************************************************************
 leaflet
                                 A QGIS plugin
 Load a webmap directly into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-11
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Tom Chadwin
        email                : tom.chadwin@nnpa.org.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import random

def detectLeaflet(mainframe):
    detectResult = mainframe.evaluateJavaScript("L.version")
    if detectResult is None:
        result = False
    else:
        result = True
    return result

def getLeafletMap(mainframe, iface):
    xyzs = mainframe.evaluateJavaScript("""
        (function (){
          urls = []
          for(var key in window) {
            var value = window[key];
            if (value instanceof L.Map) {
              for(var lyr in value._layers) {
                if (value._layers[lyr] instanceof L.TileLayer) {
                  urls.push(getXYZ(value._layers[lyr]));
                }
              }
            }
          }
          return urls;
        }());
        
        function getXYZ(lyr) {
            return lyr._url;
        }
    """)
    iface.addRasterLayer(
        "type=xyz&url=" + xyzs[0].replace(
            "{s}", random.choice("abc")).replace(
                "{r}", ""),
        "foo", "wms")