# -*- coding: utf-8 -*-
"""
/***************************************************************************
 leaflet
                                 A QGIS plugin
 Load a webmap directly into QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-05-11
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Tom Chadwin
        email                : tom.chadwin@nnpa.org.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from datetime import datetime

from web2qgis.tinycss.color3 import parse_color_string

from PyQt5.QtCore import QDir

def getTempDir():
    tempDir = os.path.join(
        unicode(QDir.tempPath()),
        'web2qgis',
        datetime.now().strftime("%Y_%m_%d-%H_%M_%S_%f"))
    if not QDir(tempDir).exists():
        QDir().mkpath(tempDir)
    return tempDir

def getScript(scriptFolder, scriptFilename):
    scriptPath = os.path.join(scriptFolder, scriptFilename)
    with open(scriptPath, 'r') as scriptFile:
        script = scriptFile.read()
    return script

def getRGBA(color):
        red, green, blue, alpha = parse_color_string(color)
        rgba = ",".join([str(int(red * 255)), str(int(green * 255)),
                         str(int(blue * 255)), str(int(alpha * 255))])
        return rgba